### ISSUE TITLE
Getting started --all-fetaures not working

### ISSUE THREAD

**Issue by NevinDry** [commonsensesoftware/more-rs-config#12]
In getting started guide : 

cargo add more-config --all-features fails : 
error: unexpected argument '--all-features' found

We should use : 
cargo add more-config --features cmd,mem,json,env,binder

**Comment by commonsensesoftware** [comment]
Thank you for reporting this. It was indeed a mistake in the documentation. Apparently, `--all-features` is only for `build` and `test`. I've added a new **all** feature and updated the documentation accordingly. Use `--features all` or `--features all,async`. The changes have been published as `2.1.1`.
